awsIoTEndpoint: "a1poqnhtwgj0le-ats.iot.eu-central-1.amazonaws.com"
awsIotRootCA: "certs/AmazonRootCA1.pem"
awsIotCert: "certs/certificate.pem.crt"
awsIotKey: "certs/private.pem.key"
awsClientId: "rbo2abt-rimac-demo"
mqttTopicIn: "in"
mqttTopicOut: "out"
udpTargetIp: "255.255.255.255"
udpPortIn: 5005
udpPortOut: 57372
