awsClientId: "rbo2abt-rimac-demo"
awsIotCert: "certs/certificate.pem.crt"
awsIotEndpoint: "a1poqnhtwgj0le-ats.iot.eu-central-1.amazonaws.com"
awsIotKey: "certs/private.pem.key"
awsIotPort: 8883
awsIotProtocol: "mqtts"
awsIotRootCA: "certs/AmazonRootCA1.pem"
mqttTopicIn: "in"
mqttTopicOut: "out"
udpIpIn: "172.17.0.1"
udpIpOut: "172.17.0.1"
udpPortIn: 5000
udpPortOut: 5005
