awsIoTEndpoint: "a7vg9mu3n5c2l-ats.iot.eu-central-1.amazonaws.com"
awsIotRootCA: "certs/AmazonRootCA1.pem"
awsIotCert: "certs/rbo2abt-go.cert.pem"
awsIotKey: "certs/rbo2abt-go.private.key"
awsClientId: "udp-mqtt-bridge"
mqttTopicIn: "topic/in"
mqttTopicOut: "topic/out"
udpTargetIp: "255.255.255.255"
udpPortIn: 5005
udpPortOut: 5006